// popularBooks.js
// AUTO-GENERATED by buildPopularBooks.mjs — do not hand-edit cover URLs.
// Edit the RAW list in buildPopularBooks.mjs and re-run that script instead.
//
// Curated best-selling / popular books with cover URLs baked in, so the app
// shows titles AND covers instantly on load with zero network calls.

const POPULAR_BOOKS = [
  {
    "title": "A Tale of Two Cities",
    "author": "Charles Dickens",
    "cover": "https://books.google.com/books/content?id=qkt4zgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-tale-of-two-cities-charles-dickens"
  },
  {
    "title": "Great Expectations",
    "author": "Charles Dickens",
    "cover": "https://books.google.com/books/content?id=ONIoAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-great-expectations-charles-dickens"
  },
  {
    "title": "Oliver Twist",
    "author": "Charles Dickens",
    "cover": "https://books.google.com/books/content?id=vK6szgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-oliver-twist-charles-dickens"
  },
  {
    "title": "The Little Prince",
    "author": "Antoine de Saint-Exupéry",
    "cover": "https://books.google.com/books/content?id=CQYg20lTHtMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-little-prince-antoine-de-saint-exup-ry"
  },
  {
    "title": "Don Quixote",
    "author": "Miguel de Cervantes",
    "cover": null,
    "key": "pop-don-quixote-miguel-de-cervantes"
  },
  {
    "title": "The Count of Monte Cristo",
    "author": "Alexandre Dumas",
    "cover": null,
    "key": "pop-the-count-of-monte-cristo-alexandre-dumas"
  },
  {
    "title": "The Three Musketeers",
    "author": "Alexandre Dumas",
    "cover": "https://books.google.com/books/content?id=MF4wEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-three-musketeers-alexandre-dumas"
  },
  {
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "cover": "https://books.google.com/books/content?id=EaP9AUuhv5IC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-pride-and-prejudice-jane-austen"
  },
  {
    "title": "Sense and Sensibility",
    "author": "Jane Austen",
    "cover": "https://books.google.com/books/content?id=Tsm4zwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-sense-and-sensibility-jane-austen"
  },
  {
    "title": "Emma",
    "author": "Jane Austen",
    "cover": null,
    "key": "pop-emma-jane-austen"
  },
  {
    "title": "Jane Eyre",
    "author": "Charlotte Brontë",
    "cover": "https://books.google.com/books/content?id=AGxyadJ1RMMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-jane-eyre-charlotte-bront"
  },
  {
    "title": "Wuthering Heights",
    "author": "Emily Brontë",
    "cover": "https://books.google.com/books/content?id=PQy7tAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-wuthering-heights-emily-bront"
  },
  {
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "cover": "https://books.google.com/books/content?id=DRagKAMw8AcC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-to-kill-a-mockingbird-harper-lee"
  },
  {
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "cover": null,
    "key": "pop-the-great-gatsby-f-scott-fitzgerald"
  },
  {
    "title": "1984",
    "author": "George Orwell",
    "cover": "https://books.google.com/books/content?id=4HQcMQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-1984-george-orwell"
  },
  {
    "title": "Animal Farm",
    "author": "George Orwell",
    "cover": "https://books.google.com/books/content?id=73wp7OGyZbAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-animal-farm-george-orwell"
  },
  {
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "cover": "https://books.google.com/books/content?id=3PabEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-brave-new-world-aldous-huxley"
  },
  {
    "title": "Fahrenheit 451",
    "author": "Ray Bradbury",
    "cover": "https://books.google.com/books/content?id=kExaAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-fahrenheit-451-ray-bradbury"
  },
  {
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "cover": "https://books.google.com/books/content?id=mZunDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-catcher-in-the-rye-j-d-salinger"
  },
  {
    "title": "Of Mice and Men",
    "author": "John Steinbeck",
    "cover": "https://books.google.com/books/content?id=YDP9EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-of-mice-and-men-john-steinbeck"
  },
  {
    "title": "The Grapes of Wrath",
    "author": "John Steinbeck",
    "cover": "https://books.google.com/books/content?id=TdhaZ6xEaBYC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-grapes-of-wrath-john-steinbeck"
  },
  {
    "title": "East of Eden",
    "author": "John Steinbeck",
    "cover": "https://books.google.com/books/content?id=OPy6E5ZhXs0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-east-of-eden-john-steinbeck"
  },
  {
    "title": "Moby-Dick",
    "author": "Herman Melville",
    "cover": null,
    "key": "pop-moby-dick-herman-melville"
  },
  {
    "title": "The Adventures of Huckleberry Finn",
    "author": "Mark Twain",
    "cover": "https://books.google.com/books/content?id=53CKzQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-adventures-of-huckleberry-finn-mark-twain"
  },
  {
    "title": "The Adventures of Tom Sawyer",
    "author": "Mark Twain",
    "cover": "https://books.google.com/books/content?id=t5yFTpIJYhcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-adventures-of-tom-sawyer-mark-twain"
  },
  {
    "title": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "cover": null,
    "key": "pop-crime-and-punishment-fyodor-dostoevsky"
  },
  {
    "title": "The Brothers Karamazov",
    "author": "Fyodor Dostoevsky",
    "cover": "https://books.google.com/books/content?id=BZvXZ1au0VcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-brothers-karamazov-fyodor-dostoevsky"
  },
  {
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "cover": "https://books.google.com/books/content?id=R1gpAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-war-and-peace-leo-tolstoy"
  },
  {
    "title": "Anna Karenina",
    "author": "Leo Tolstoy",
    "cover": "https://books.google.com/books/content?id=bB2ftgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-anna-karenina-leo-tolstoy"
  },
  {
    "title": "Les Misérables",
    "author": "Victor Hugo",
    "cover": "https://books.google.com/books/content?id=Qn7tswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-les-mis-rables-victor-hugo"
  },
  {
    "title": "The Hunchback of Notre-Dame",
    "author": "Victor Hugo",
    "cover": "https://books.google.com/books/content?id=Dk_dE7Vp8S4C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-hunchback-of-notre-dame-victor-hugo"
  },
  {
    "title": "Frankenstein",
    "author": "Mary Shelley",
    "cover": "https://books.google.com/books/content?id=UL6Cwv2Z1iQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-frankenstein-mary-shelley"
  },
  {
    "title": "Dracula",
    "author": "Bram Stoker",
    "cover": "https://books.google.com/books/content?id=jI_mDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-dracula-bram-stoker"
  },
  {
    "title": "The Picture of Dorian Gray",
    "author": "Oscar Wilde",
    "cover": "https://books.google.com/books/content?id=wFp2CQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-picture-of-dorian-gray-oscar-wilde"
  },
  {
    "title": "Heart of Darkness",
    "author": "Joseph Conrad",
    "cover": "https://books.google.com/books/content?id=y5NCEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-heart-of-darkness-joseph-conrad"
  },
  {
    "title": "The Old Man and the Sea",
    "author": "Ernest Hemingway",
    "cover": "https://books.google.com/books/content?id=K1cIZmFe7KoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-old-man-and-the-sea-ernest-hemingway"
  },
  {
    "title": "For Whom the Bell Tolls",
    "author": "Ernest Hemingway",
    "cover": "https://books.google.com/books/content?id=TdVQAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-for-whom-the-bell-tolls-ernest-hemingway"
  },
  {
    "title": "One Hundred Years of Solitude",
    "author": "Gabriel García Márquez",
    "cover": "https://books.google.com/books/content?id=RyGVAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-one-hundred-years-of-solitude-gabriel-garc-a-m-rquez"
  },
  {
    "title": "Love in the Time of Cholera",
    "author": "Gabriel García Márquez",
    "cover": "https://books.google.com/books/content?id=E7iFBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-love-in-the-time-of-cholera-gabriel-garc-a-m-rquez"
  },
  {
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "cover": "https://books.google.com/books/content?id=FEL8DlqjYEkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-alchemist-paulo-coelho"
  },
  {
    "title": "Lord of the Flies",
    "author": "William Golding",
    "cover": null,
    "key": "pop-lord-of-the-flies-william-golding"
  },
  {
    "title": "Catch-22",
    "author": "Joseph Heller",
    "cover": "https://books.google.com/books/content?id=T8j0KOiR1DoC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-catch-22-joseph-heller"
  },
  {
    "title": "Slaughterhouse-Five",
    "author": "Kurt Vonnegut",
    "cover": "https://books.google.com/books/content?id=w9E8PgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-slaughterhouse-five-kurt-vonnegut"
  },
  {
    "title": "The Bell Jar",
    "author": "Sylvia Plath",
    "cover": "https://books.google.com/books/content?id=vRPtAQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-bell-jar-sylvia-plath"
  },
  {
    "title": "Beloved",
    "author": "Toni Morrison",
    "cover": "https://books.google.com/books/content?id=J9QKHyiUJbYC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-beloved-toni-morrison"
  },
  {
    "title": "Their Eyes Were Watching God",
    "author": "Zora Neale Hurston",
    "cover": "https://books.google.com/books/content?id=9UuQPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-their-eyes-were-watching-god-zora-neale-hurston"
  },
  {
    "title": "The Color Purple",
    "author": "Alice Walker",
    "cover": "https://books.google.com/books/content?id=r_fC_s64AH0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-color-purple-alice-walker"
  },
  {
    "title": "A Thousand Splendid Suns",
    "author": "Khaled Hosseini",
    "cover": "https://books.google.com/books/content?id=3vo0NQbIN2YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-a-thousand-splendid-suns-khaled-hosseini"
  },
  {
    "title": "The Kite Runner",
    "author": "Khaled Hosseini",
    "cover": "https://books.google.com/books/content?id=KUMIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-kite-runner-khaled-hosseini"
  },
  {
    "title": "Life of Pi",
    "author": "Yann Martel",
    "cover": "https://books.google.com/books/content?id=O8ZaEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-life-of-pi-yann-martel"
  },
  {
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "cover": "https://books.google.com/books/content?id=7_bQPm3R4NgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-book-thief-markus-zusak"
  },
  {
    "title": "The Handmaid's Tale",
    "author": "Margaret Atwood",
    "cover": "https://books.google.com/books/content?id=Iak7PgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-handmaid-s-tale-margaret-atwood"
  },
  {
    "title": "Never Let Me Go",
    "author": "Kazuo Ishiguro",
    "cover": "https://books.google.com/books/content?id=qLfZf7f5_pkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-never-let-me-go-kazuo-ishiguro"
  },
  {
    "title": "The Remains of the Day",
    "author": "Kazuo Ishiguro",
    "cover": "https://books.google.com/books/content?id=MSurBex2xcUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-remains-of-the-day-kazuo-ishiguro"
  },
  {
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=j82bQf8ziykC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-hobbit-j-r-r-tolkien"
  },
  {
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=xFr92V2k3PIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-lord-of-the-rings-j-r-r-tolkien"
  },
  {
    "title": "The Silmarillion",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=k-Vh_Lnyb-IC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-silmarillion-j-r-r-tolkien"
  },
  {
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=djf_RQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-philosopher-s-stone-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Chamber of Secrets",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=SJnHBAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-chamber-of-secrets-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Prisoner of Azkaban",
    "author": "J.K. Rowling",
    "cover": null,
    "key": "pop-harry-potter-and-the-prisoner-of-azkaban-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Goblet of Fire",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=etukl7GfrxQC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-goblet-of-fire-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Order of the Phoenix",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=AnjKOAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-order-of-the-phoenix-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Half-Blood Prince",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=ZFuaPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-half-blood-prince-j-k-rowling"
  },
  {
    "title": "Harry Potter and the Deathly Hallows",
    "author": "J.K. Rowling",
    "cover": "https://books.google.com/books/content?id=8rMBuwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-harry-potter-and-the-deathly-hallows-j-k-rowling"
  },
  {
    "title": "The Lion, the Witch and the Wardrobe",
    "author": "C.S. Lewis",
    "cover": "https://books.google.com/books/content?id=gY6RQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-lion-the-witch-and-the-wardrobe-c-s-lewis"
  },
  {
    "title": "A Game of Thrones",
    "author": "George R.R. Martin",
    "cover": "https://books.google.com/books/content?id=5NomkK4EV68C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-a-game-of-thrones-george-r-r-martin"
  },
  {
    "title": "A Clash of Kings",
    "author": "George R.R. Martin",
    "cover": "https://books.google.com/books/content?id=jxlbAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-clash-of-kings-george-r-r-martin"
  },
  {
    "title": "A Storm of Swords",
    "author": "George R.R. Martin",
    "cover": "https://books.google.com/books/content?id=YxpbAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-storm-of-swords-george-r-r-martin"
  },
  {
    "title": "The Name of the Wind",
    "author": "Patrick Rothfuss",
    "cover": "https://books.google.com/books/content?id=OlmJEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-name-of-the-wind-patrick-rothfuss"
  },
  {
    "title": "The Way of Kings",
    "author": "Brandon Sanderson",
    "cover": "https://books.google.com/books/content?id=d-nv9nnEnVwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-way-of-kings-brandon-sanderson"
  },
  {
    "title": "Mistborn: The Final Empire",
    "author": "Brandon Sanderson",
    "cover": "https://books.google.com/books/content?id=t_ZYYXZq4RgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-mistborn-the-final-empire-brandon-sanderson"
  },
  {
    "title": "The Eye of the World",
    "author": "Robert Jordan",
    "cover": "https://books.google.com/books/content?id=1PgKPuFIz1kC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-eye-of-the-world-robert-jordan"
  },
  {
    "title": "American Gods",
    "author": "Neil Gaiman",
    "cover": "https://books.google.com/books/content?id=fXfJCKXp5-kC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-american-gods-neil-gaiman"
  },
  {
    "title": "Good Omens",
    "author": "Neil Gaiman",
    "cover": "https://books.google.com/books/content?id=B7FL6zzN_FsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-good-omens-neil-gaiman"
  },
  {
    "title": "The Color of Magic",
    "author": "Terry Pratchett",
    "cover": "https://books.google.com/books/content?id=0OLrngEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-color-of-magic-terry-pratchett"
  },
  {
    "title": "Dune",
    "author": "Frank Herbert",
    "cover": "https://books.google.com/books/content?id=AQk_EAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-dune-frank-herbert"
  },
  {
    "title": "Foundation",
    "author": "Isaac Asimov",
    "cover": "https://books.google.com/books/content?id=Za8NAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-foundation-isaac-asimov"
  },
  {
    "title": "I, Robot",
    "author": "Isaac Asimov",
    "cover": "https://books.google.com/books/content?id=P9zPAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-i-robot-isaac-asimov"
  },
  {
    "title": "Ender's Game",
    "author": "Orson Scott Card",
    "cover": "https://books.google.com/books/content?id=Ojqi8KbWuLwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-ender-s-game-orson-scott-card"
  },
  {
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "cover": "https://books.google.com/books/content?id=DmUr6q1EDYMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-hitchhiker-s-guide-to-the-galaxy-douglas-adams"
  },
  {
    "title": "Ready Player One",
    "author": "Ernest Cline",
    "cover": "https://books.google.com/books/content?id=8qs1-ypf7e0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-ready-player-one-ernest-cline"
  },
  {
    "title": "The Martian",
    "author": "Andy Weir",
    "cover": "https://books.google.com/books/content?id=uQ-PEAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-martian-andy-weir"
  },
  {
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "cover": "https://books.google.com/books/content?id=CnSJEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-project-hail-mary-andy-weir"
  },
  {
    "title": "Neuromancer",
    "author": "William Gibson",
    "cover": "https://books.google.com/books/content?id=Bd_UZAdvUDIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-neuromancer-william-gibson"
  },
  {
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "cover": "https://books.google.com/books/content?id=PiCWSgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-do-androids-dream-of-electric-sheep-philip-k-dick"
  },
  {
    "title": "The Left Hand of Darkness",
    "author": "Ursula K. Le Guin",
    "cover": "https://books.google.com/books/content?id=zhERCgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-left-hand-of-darkness-ursula-k-le-guin"
  },
  {
    "title": "A Wizard of Earthsea",
    "author": "Ursula K. Le Guin",
    "cover": "https://books.google.com/books/content?id=bU6xAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-wizard-of-earthsea-ursula-k-le-guin"
  },
  {
    "title": "The Fellowship of the Ring",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=xFr92V2k3PIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-fellowship-of-the-ring-j-r-r-tolkien"
  },
  {
    "title": "Eragon",
    "author": "Christopher Paolini",
    "cover": "https://books.google.com/books/content?id=wYAkAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-eragon-christopher-paolini"
  },
  {
    "title": "The Lightning Thief",
    "author": "Rick Riordan",
    "cover": "https://books.google.com/books/content?id=IQKqlAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-lightning-thief-rick-riordan"
  },
  {
    "title": "The Da Vinci Code",
    "author": "Dan Brown",
    "cover": "https://books.google.com/books/content?id=6-pmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-da-vinci-code-dan-brown"
  },
  {
    "title": "Angels & Demons",
    "author": "Dan Brown",
    "cover": "https://books.google.com/books/content?id=K__fyN2gl9gC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-angels-demons-dan-brown"
  },
  {
    "title": "The Girl with the Dragon Tattoo",
    "author": "Stieg Larsson",
    "cover": "https://books.google.com/books/content?id=WrL9de30FDMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-girl-with-the-dragon-tattoo-stieg-larsson"
  },
  {
    "title": "Gone Girl",
    "author": "Gillian Flynn",
    "cover": "https://books.google.com/books/content?id=L25K1tY5WyoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-gone-girl-gillian-flynn"
  },
  {
    "title": "The Girl on the Train",
    "author": "Paula Hawkins",
    "cover": "https://books.google.com/books/content?id=nfziDAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-girl-on-the-train-paula-hawkins"
  },
  {
    "title": "The Silent Patient",
    "author": "Alex Michaelides",
    "cover": "https://books.google.com/books/content?id=a6NnDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-silent-patient-alex-michaelides"
  },
  {
    "title": "And Then There Were None",
    "author": "Agatha Christie",
    "cover": "https://books.google.com/books/content?id=qLaCgNBGCv4C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-and-then-there-were-none-agatha-christie"
  },
  {
    "title": "Murder on the Orient Express",
    "author": "Agatha Christie",
    "cover": "https://books.google.com/books/content?id=KKZ2DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-murder-on-the-orient-express-agatha-christie"
  },
  {
    "title": "The Murder of Roger Ackroyd",
    "author": "Agatha Christie",
    "cover": "https://books.google.com/books/content?id=Y5KOEAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-murder-of-roger-ackroyd-agatha-christie"
  },
  {
    "title": "The Hound of the Baskervilles",
    "author": "Arthur Conan Doyle",
    "cover": "https://books.google.com/books/content?id=Kr2u4ikVg64C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-hound-of-the-baskervilles-arthur-conan-doyle"
  },
  {
    "title": "The Firm",
    "author": "John Grisham",
    "cover": "https://books.google.com/books/content?id=xE4_NgvJtggC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-firm-john-grisham"
  },
  {
    "title": "A Time to Kill",
    "author": "John Grisham",
    "cover": "https://books.google.com/books/content?id=Xp39K0c0IaEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-a-time-to-kill-john-grisham"
  },
  {
    "title": "The Pelican Brief",
    "author": "John Grisham",
    "cover": "https://books.google.com/books/content?id=2w0LnhBkZR0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-pelican-brief-john-grisham"
  },
  {
    "title": "The Shining",
    "author": "Stephen King",
    "cover": "https://books.google.com/books/content?id=QABREQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-shining-stephen-king"
  },
  {
    "title": "It",
    "author": "Stephen King",
    "cover": "https://books.google.com/books/content?id=iCWgDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-it-stephen-king"
  },
  {
    "title": "The Stand",
    "author": "Stephen King",
    "cover": "https://books.google.com/books/content?id=LC32OW8iVUQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-stand-stephen-king"
  },
  {
    "title": "Misery",
    "author": "Stephen King",
    "cover": "https://books.google.com/books/content?id=QbUACwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-misery-stephen-king"
  },
  {
    "title": "Carrie",
    "author": "Stephen King",
    "cover": "https://books.google.com/books/content?id=OABREQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-carrie-stephen-king"
  },
  {
    "title": "The Bourne Identity",
    "author": "Robert Ludlum",
    "cover": "https://books.google.com/books/content?id=BebwoOZCPr0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-bourne-identity-robert-ludlum"
  },
  {
    "title": "The Girl Who Played with Fire",
    "author": "Stieg Larsson",
    "cover": "https://books.google.com/books/content?id=UvK1Slvkz3MC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-girl-who-played-with-fire-stieg-larsson"
  },
  {
    "title": "Big Little Lies",
    "author": "Liane Moriarty",
    "cover": "https://books.google.com/books/content?id=xOaKAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-big-little-lies-liane-moriarty"
  },
  {
    "title": "The Reversal",
    "author": "Michael Connelly",
    "cover": "https://books.google.com/books/content?id=BVLsF93bLOoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-reversal-michael-connelly"
  },
  {
    "title": "Along Came a Spider",
    "author": "James Patterson",
    "cover": "https://books.google.com/books/content?id=EA09PgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-along-came-a-spider-james-patterson"
  },
  {
    "title": "The Cuckoo's Calling",
    "author": "Robert Galbraith",
    "cover": "https://books.google.com/books/content?id=phQtnwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-cuckoo-s-calling-robert-galbraith"
  },
  {
    "title": "The Notebook",
    "author": "Nicholas Sparks",
    "cover": "https://books.google.com/books/content?id=egE-PgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-notebook-nicholas-sparks"
  },
  {
    "title": "A Walk to Remember",
    "author": "Nicholas Sparks",
    "cover": "https://books.google.com/books/content?id=kuLSvAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-walk-to-remember-nicholas-sparks"
  },
  {
    "title": "Me Before You",
    "author": "Jojo Moyes",
    "cover": "https://books.google.com/books/content?id=rTYEyWrXLO0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-me-before-you-jojo-moyes"
  },
  {
    "title": "Outlander",
    "author": "Diana Gabaldon",
    "cover": "https://books.google.com/books/content?id=7iF6BgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-outlander-diana-gabaldon"
  },
  {
    "title": "It Ends with Us",
    "author": "Colleen Hoover",
    "cover": "https://books.google.com/books/content?id=peTPCgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-it-ends-with-us-colleen-hoover"
  },
  {
    "title": "Verity",
    "author": "Colleen Hoover",
    "cover": "https://books.google.com/books/content?id=TJZWEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-verity-colleen-hoover"
  },
  {
    "title": "The Fault in Our Stars",
    "author": "John Green",
    "cover": "https://books.google.com/books/content?id=UzqVUdEtLDwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-fault-in-our-stars-john-green"
  },
  {
    "title": "Pride and Prejudice and Zombies",
    "author": "Seth Grahame-Smith",
    "cover": "https://books.google.com/books/content?id=B5pUjwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-pride-and-prejudice-and-zombies-seth-grahame-smith"
  },
  {
    "title": "The Time Traveler's Wife",
    "author": "Audrey Niffenegger",
    "cover": "https://books.google.com/books/content?id=izm3EQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-time-traveler-s-wife-audrey-niffenegger"
  },
  {
    "title": "Where the Crawdads Sing",
    "author": "Delia Owens",
    "cover": "https://books.google.com/books/content?id=CGVDDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-where-the-crawdads-sing-delia-owens"
  },
  {
    "title": "Normal People",
    "author": "Sally Rooney",
    "cover": "https://books.google.com/books/content?id=kwBlDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-normal-people-sally-rooney"
  },
  {
    "title": "The Seven Husbands of Evelyn Hugo",
    "author": "Taylor Jenkins Reid",
    "cover": "https://books.google.com/books/content?id=NdAmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-seven-husbands-of-evelyn-hugo-taylor-jenkins-reid"
  },
  {
    "title": "Bridget Jones's Diary",
    "author": "Helen Fielding",
    "cover": "https://books.google.com/books/content?id=qa1pPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-bridget-jones-s-diary-helen-fielding"
  },
  {
    "title": "The Hunger Games",
    "author": "Suzanne Collins",
    "cover": "https://books.google.com/books/content?id=Yz8Fnw0PlEQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-hunger-games-suzanne-collins"
  },
  {
    "title": "Catching Fire",
    "author": "Suzanne Collins",
    "cover": "https://books.google.com/books/content?id=rBjcAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-catching-fire-suzanne-collins"
  },
  {
    "title": "Mockingjay",
    "author": "Suzanne Collins",
    "cover": null,
    "key": "pop-mockingjay-suzanne-collins"
  },
  {
    "title": "Twilight",
    "author": "Stephenie Meyer",
    "cover": "https://books.google.com/books/content?id=lGjFtMRqp_YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-twilight-stephenie-meyer"
  },
  {
    "title": "New Moon",
    "author": "Stephenie Meyer",
    "cover": "https://books.google.com/books/content?id=8YTOPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-new-moon-stephenie-meyer"
  },
  {
    "title": "Divergent",
    "author": "Veronica Roth",
    "cover": "https://books.google.com/books/content?id=KZRDDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-divergent-veronica-roth"
  },
  {
    "title": "The Maze Runner",
    "author": "James Dashner",
    "cover": "https://books.google.com/books/content?id=yo5GBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-maze-runner-james-dashner"
  },
  {
    "title": "The Perks of Being a Wallflower",
    "author": "Stephen Chbosky",
    "cover": "https://books.google.com/books/content?id=xFNG764pnOgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-perks-of-being-a-wallflower-stephen-chbosky"
  },
  {
    "title": "Looking for Alaska",
    "author": "John Green",
    "cover": null,
    "key": "pop-looking-for-alaska-john-green"
  },
  {
    "title": "The Giver",
    "author": "Lois Lowry",
    "cover": "https://books.google.com/books/content?id=weCEDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-giver-lois-lowry"
  },
  {
    "title": "Wonder",
    "author": "R.J. Palacio",
    "cover": "https://books.google.com/books/content?id=oPHiDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-wonder-r-j-palacio"
  },
  {
    "title": "Charlotte's Web",
    "author": "E.B. White",
    "cover": "https://books.google.com/books/content?id=NK6IjRpjymAC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-charlotte-s-web-e-b-white"
  },
  {
    "title": "Matilda",
    "author": "Roald Dahl",
    "cover": "https://books.google.com/books/content?id=_uIlE7DkAzYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-matilda-roald-dahl"
  },
  {
    "title": "Charlie and the Chocolate Factory",
    "author": "Roald Dahl",
    "cover": "https://books.google.com/books/content?id=7tYWAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-charlie-and-the-chocolate-factory-roald-dahl"
  },
  {
    "title": "The BFG",
    "author": "Roald Dahl",
    "cover": "https://books.google.com/books/content?id=quybcXrFhCIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-bfg-roald-dahl"
  },
  {
    "title": "Diary of a Wimpy Kid",
    "author": "Jeff Kinney",
    "cover": "https://books.google.com/books/content?id=8MXK_KrHOZYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-diary-of-a-wimpy-kid-jeff-kinney"
  },
  {
    "title": "The Cat in the Hat",
    "author": "Dr. Seuss",
    "cover": "https://books.google.com/books/content?id=rFfhAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-cat-in-the-hat-dr-seuss"
  },
  {
    "title": "Green Eggs and Ham",
    "author": "Dr. Seuss",
    "cover": "https://books.google.com/books/content?id=ZK7xAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-green-eggs-and-ham-dr-seuss"
  },
  {
    "title": "Oh, the Places You'll Go!",
    "author": "Dr. Seuss",
    "cover": "https://books.google.com/books/content?id=1q_xAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-oh-the-places-you-ll-go-dr-seuss"
  },
  {
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "cover": "https://books.google.com/books/content?id=1EiJAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-sapiens-a-brief-history-of-humankind-yuval-noah-harari"
  },
  {
    "title": "Homo Deus",
    "author": "Yuval Noah Harari",
    "cover": "https://books.google.com/books/content?id=XgksEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-homo-deus-yuval-noah-harari"
  },
  {
    "title": "Atomic Habits",
    "author": "James Clear",
    "cover": "https://books.google.com/books/content?id=WmqyDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-atomic-habits-james-clear"
  },
  {
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen R. Covey",
    "cover": "https://books.google.com/books/content?id=upUxaNWSaRIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-7-habits-of-highly-effective-people-stephen-r-covey"
  },
  {
    "title": "How to Win Friends and Influence People",
    "author": "Dale Carnegie",
    "cover": "https://books.google.com/books/content?id=hCf-DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-how-to-win-friends-and-influence-people-dale-carnegie"
  },
  {
    "title": "Think and Grow Rich",
    "author": "Napoleon Hill",
    "cover": "https://books.google.com/books/content?id=sJIJEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-think-and-grow-rich-napoleon-hill"
  },
  {
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki",
    "cover": "https://books.google.com/books/content?id=kRqeDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-rich-dad-poor-dad-robert-t-kiyosaki"
  },
  {
    "title": "The Power of Now",
    "author": "Eckhart Tolle",
    "cover": "https://books.google.com/books/content?id=NFQ7DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-power-of-now-eckhart-tolle"
  },
  {
    "title": "A New Earth",
    "author": "Eckhart Tolle",
    "cover": "https://books.google.com/books/content?id=JScjn-NRFaUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-a-new-earth-eckhart-tolle"
  },
  {
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "cover": "https://books.google.com/books/content?id=yng_CwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-subtle-art-of-not-giving-a-f-ck-mark-manson"
  },
  {
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "cover": "https://books.google.com/books/content?id=ZuKTvERuPG8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-thinking-fast-and-slow-daniel-kahneman"
  },
  {
    "title": "Outliers",
    "author": "Malcolm Gladwell",
    "cover": "https://books.google.com/books/content?id=ialrgIT41OAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-outliers-malcolm-gladwell"
  },
  {
    "title": "The Tipping Point",
    "author": "Malcolm Gladwell",
    "cover": "https://books.google.com/books/content?id=mUZ7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-tipping-point-malcolm-gladwell"
  },
  {
    "title": "Educated",
    "author": "Tara Westover",
    "cover": "https://books.google.com/books/content?id=2ObWDgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-educated-tara-westover"
  },
  {
    "title": "Becoming",
    "author": "Michelle Obama",
    "cover": "https://books.google.com/books/content?id=rMGoDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-becoming-michelle-obama"
  },
  {
    "title": "The Diary of a Young Girl",
    "author": "Anne Frank",
    "cover": "https://books.google.com/books/content?id=kRE8xxCmUcMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-diary-of-a-young-girl-anne-frank"
  },
  {
    "title": "Man's Search for Meaning",
    "author": "Viktor E. Frankl",
    "cover": "https://books.google.com/books/content?id=umJ8DgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-man-s-search-for-meaning-viktor-e-frankl"
  },
  {
    "title": "Quiet: The Power of Introverts",
    "author": "Susan Cain",
    "cover": "https://books.google.com/books/content?id=O6gZJa9kdlYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-quiet-the-power-of-introverts-susan-cain"
  },
  {
    "title": "The Body Keeps the Score",
    "author": "Bessel van der Kolk",
    "cover": "https://books.google.com/books/content?id=Yv2nywEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-body-keeps-the-score-bessel-van-der-kolk"
  },
  {
    "title": "The Four Agreements",
    "author": "Don Miguel Ruiz",
    "cover": "https://books.google.com/books/content?id=hzVxiw2DiOsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-four-agreements-don-miguel-ruiz"
  },
  {
    "title": "The Power of Habit",
    "author": "Charles Duhigg",
    "cover": "https://books.google.com/books/content?id=oFYNngEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-power-of-habit-charles-duhigg"
  },
  {
    "title": "Born a Crime",
    "author": "Trevor Noah",
    "cover": "https://books.google.com/books/content?id=dAzJCwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-born-a-crime-trevor-noah"
  },
  {
    "title": "The Gifts of Imperfection",
    "author": "Brené Brown",
    "cover": "https://books.google.com/books/content?id=0kPXDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-gifts-of-imperfection-bren-brown"
  },
  {
    "title": "A Brief History of Time",
    "author": "Stephen Hawking",
    "cover": "https://books.google.com/books/content?id=eUzqAAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-brief-history-of-time-stephen-hawking"
  },
  {
    "title": "Steve Jobs",
    "author": "Walter Isaacson",
    "cover": "https://books.google.com/books/content?id=8U2oAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-steve-jobs-walter-isaacson"
  },
  {
    "title": "Siddhartha",
    "author": "Hermann Hesse",
    "cover": "https://books.google.com/books/content?id=1HbVmUsuGiYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-siddhartha-hermann-hesse"
  },
  {
    "title": "Steppenwolf",
    "author": "Hermann Hesse",
    "cover": "https://books.google.com/books/content?id=HEyhEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-steppenwolf-hermann-hesse"
  },
  {
    "title": "The Stranger",
    "author": "Albert Camus",
    "cover": "https://books.google.com/books/content?id=uxfuAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-stranger-albert-camus"
  },
  {
    "title": "The Trial",
    "author": "Franz Kafka",
    "cover": "https://books.google.com/books/content?id=jA_ADwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-trial-franz-kafka"
  },
  {
    "title": "The Metamorphosis",
    "author": "Franz Kafka",
    "cover": "https://books.google.com/books/content?id=ZRYfAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-metamorphosis-franz-kafka"
  },
  {
    "title": "A Clockwork Orange",
    "author": "Anthony Burgess",
    "cover": "https://books.google.com/books/content?id=bgpJn-Oq22MC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-a-clockwork-orange-anthony-burgess"
  },
  {
    "title": "The Road",
    "author": "Cormac McCarthy",
    "cover": "https://books.google.com/books/content?id=WIKrD-GKehQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-road-cormac-mccarthy"
  },
  {
    "title": "Blood Meridian",
    "author": "Cormac McCarthy",
    "cover": "https://books.google.com/books/content?id=s-QzccStux4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-blood-meridian-cormac-mccarthy"
  },
  {
    "title": "No Country for Old Men",
    "author": "Cormac McCarthy",
    "cover": "https://books.google.com/books/content?id=3Ksa5vqnc8QC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-no-country-for-old-men-cormac-mccarthy"
  },
  {
    "title": "The Secret History",
    "author": "Donna Tartt",
    "cover": "https://books.google.com/books/content?id=VO2w8m-ZAeMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-secret-history-donna-tartt"
  },
  {
    "title": "The Goldfinch",
    "author": "Donna Tartt",
    "cover": "https://books.google.com/books/content?id=T2CA83gbtM8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-goldfinch-donna-tartt"
  },
  {
    "title": "A Little Life",
    "author": "Hanya Yanagihara",
    "cover": "https://books.google.com/books/content?id=0IQd0QEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-a-little-life-hanya-yanagihara"
  },
  {
    "title": "The Midnight Library",
    "author": "Matt Haig",
    "cover": "https://books.google.com/books/content?id=63fYDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-midnight-library-matt-haig"
  },
  {
    "title": "Klara and the Sun",
    "author": "Kazuo Ishiguro",
    "cover": "https://books.google.com/books/content?id=S7jrDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-klara-and-the-sun-kazuo-ishiguro"
  },
  {
    "title": "Circe",
    "author": "Madeline Miller",
    "cover": "https://books.google.com/books/content?id=dyikEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-circe-madeline-miller"
  },
  {
    "title": "The Song of Achilles",
    "author": "Madeline Miller",
    "cover": "https://books.google.com/books/content?id=JUMIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-song-of-achilles-madeline-miller"
  },
  {
    "title": "Dune Messiah",
    "author": "Frank Herbert",
    "cover": "https://books.google.com/books/content?id=neiwAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-dune-messiah-frank-herbert"
  },
  {
    "title": "The Two Towers",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=12e8PJ2T7sQC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-two-towers-j-r-r-tolkien"
  },
  {
    "title": "The Return of the King",
    "author": "J.R.R. Tolkien",
    "cover": "https://books.google.com/books/content?id=K-dCAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "key": "pop-the-return-of-the-king-j-r-r-tolkien"
  },
  {
    "title": "The Wise Man's Fear",
    "author": "Patrick Rothfuss",
    "cover": "https://books.google.com/books/content?id=6FmJEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-wise-man-s-fear-patrick-rothfuss"
  },
  {
    "title": "Words of Radiance",
    "author": "Brandon Sanderson",
    "cover": "https://books.google.com/books/content?id=kYjqAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-words-of-radiance-brandon-sanderson"
  },
  {
    "title": "The Power of Positive Thinking",
    "author": "Norman Vincent Peale",
    "cover": null,
    "key": "pop-the-power-of-positive-thinking-norman-vincent-peale"
  },
  {
    "title": "Can't Hurt Me",
    "author": "David Goggins",
    "cover": "https://books.google.com/books/content?id=OSchEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-can-t-hurt-me-david-goggins"
  },
  {
    "title": "Deep Work",
    "author": "Cal Newport",
    "cover": "https://books.google.com/books/content?id=lZpFCgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-deep-work-cal-newport"
  },
  {
    "title": "Ikigai",
    "author": "Héctor García",
    "cover": "https://books.google.com/books/content?id=4UCnDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-ikigai-h-ctor-garc-a"
  },
  {
    "title": "The 48 Laws of Power",
    "author": "Robert Greene",
    "cover": "https://books.google.com/books/content?id=afCxg5sogvAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "key": "pop-the-48-laws-of-power-robert-greene"
  }
];

export default POPULAR_BOOKS;
