// popularBooks.js
// A curated, hardcoded list of widely-recognised best-selling / popular books
// across genres. Used to seed the instant-search cache so typing a well-known
// title or author hits immediately, with no network call.
//
// Why hardcoded instead of querying Google Books for "bestseller"?
// Searching the API for "bestseller" returns books with the word "bestseller"
// in the title — junk — not actual best-sellers. This list is real titles.
//
// `key` is a stable synthetic id (slug of title+author). Covers are intentionally
// omitted here; the dropdown shows the 📖 placeholder for cached items, and real
// cover/genre/page data is still fetched from Google Books once a book is added
// or recommended. Keeping covers out of this list keeps it tiny and offline-first.

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

// [title, author] pairs. ~165 entries across classics, modern fiction,
// fantasy/sci-fi, thriller/mystery, romance, YA, and non-fiction/self-help.
const RAW = [
  // ---- Classics / literary ----
  ["A Tale of Two Cities", "Charles Dickens"],
  ["Great Expectations", "Charles Dickens"],
  ["Oliver Twist", "Charles Dickens"],
  ["The Little Prince", "Antoine de Saint-Exupéry"],
  ["Don Quixote", "Miguel de Cervantes"],
  ["The Count of Monte Cristo", "Alexandre Dumas"],
  ["The Three Musketeers", "Alexandre Dumas"],
  ["Pride and Prejudice", "Jane Austen"],
  ["Sense and Sensibility", "Jane Austen"],
  ["Emma", "Jane Austen"],
  ["Jane Eyre", "Charlotte Brontë"],
  ["Wuthering Heights", "Emily Brontë"],
  ["To Kill a Mockingbird", "Harper Lee"],
  ["The Great Gatsby", "F. Scott Fitzgerald"],
  ["1984", "George Orwell"],
  ["Animal Farm", "George Orwell"],
  ["Brave New World", "Aldous Huxley"],
  ["Fahrenheit 451", "Ray Bradbury"],
  ["The Catcher in the Rye", "J.D. Salinger"],
  ["Of Mice and Men", "John Steinbeck"],
  ["The Grapes of Wrath", "John Steinbeck"],
  ["East of Eden", "John Steinbeck"],
  ["Moby-Dick", "Herman Melville"],
  ["The Adventures of Huckleberry Finn", "Mark Twain"],
  ["The Adventures of Tom Sawyer", "Mark Twain"],
  ["Crime and Punishment", "Fyodor Dostoevsky"],
  ["The Brothers Karamazov", "Fyodor Dostoevsky"],
  ["War and Peace", "Leo Tolstoy"],
  ["Anna Karenina", "Leo Tolstoy"],
  ["Les Misérables", "Victor Hugo"],
  ["The Hunchback of Notre-Dame", "Victor Hugo"],
  ["Frankenstein", "Mary Shelley"],
  ["Dracula", "Bram Stoker"],
  ["The Picture of Dorian Gray", "Oscar Wilde"],
  ["Heart of Darkness", "Joseph Conrad"],
  ["The Old Man and the Sea", "Ernest Hemingway"],
  ["For Whom the Bell Tolls", "Ernest Hemingway"],
  ["One Hundred Years of Solitude", "Gabriel García Márquez"],
  ["Love in the Time of Cholera", "Gabriel García Márquez"],
  ["The Alchemist", "Paulo Coelho"],
  ["Lord of the Flies", "William Golding"],
  ["Catch-22", "Joseph Heller"],
  ["Slaughterhouse-Five", "Kurt Vonnegut"],
  ["The Bell Jar", "Sylvia Plath"],
  ["Beloved", "Toni Morrison"],
  ["Their Eyes Were Watching God", "Zora Neale Hurston"],
  ["The Color Purple", "Alice Walker"],
  ["A Thousand Splendid Suns", "Khaled Hosseini"],
  ["The Kite Runner", "Khaled Hosseini"],
  ["Life of Pi", "Yann Martel"],
  ["The Book Thief", "Markus Zusak"],
  ["The Handmaid's Tale", "Margaret Atwood"],
  ["Never Let Me Go", "Kazuo Ishiguro"],
  ["The Remains of the Day", "Kazuo Ishiguro"],

  // ---- Fantasy / sci-fi ----
  ["The Hobbit", "J.R.R. Tolkien"],
  ["The Lord of the Rings", "J.R.R. Tolkien"],
  ["The Silmarillion", "J.R.R. Tolkien"],
  ["Harry Potter and the Philosopher's Stone", "J.K. Rowling"],
  ["Harry Potter and the Chamber of Secrets", "J.K. Rowling"],
  ["Harry Potter and the Prisoner of Azkaban", "J.K. Rowling"],
  ["Harry Potter and the Goblet of Fire", "J.K. Rowling"],
  ["Harry Potter and the Order of the Phoenix", "J.K. Rowling"],
  ["Harry Potter and the Half-Blood Prince", "J.K. Rowling"],
  ["Harry Potter and the Deathly Hallows", "J.K. Rowling"],
  ["The Lion, the Witch and the Wardrobe", "C.S. Lewis"],
  ["A Game of Thrones", "George R.R. Martin"],
  ["A Clash of Kings", "George R.R. Martin"],
  ["A Storm of Swords", "George R.R. Martin"],
  ["The Name of the Wind", "Patrick Rothfuss"],
  ["The Way of Kings", "Brandon Sanderson"],
  ["Mistborn: The Final Empire", "Brandon Sanderson"],
  ["The Eye of the World", "Robert Jordan"],
  ["American Gods", "Neil Gaiman"],
  ["Good Omens", "Neil Gaiman"],
  ["The Color of Magic", "Terry Pratchett"],
  ["Dune", "Frank Herbert"],
  ["Foundation", "Isaac Asimov"],
  ["I, Robot", "Isaac Asimov"],
  ["Ender's Game", "Orson Scott Card"],
  ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams"],
  ["Ready Player One", "Ernest Cline"],
  ["The Martian", "Andy Weir"],
  ["Project Hail Mary", "Andy Weir"],
  ["Neuromancer", "William Gibson"],
  ["Do Androids Dream of Electric Sheep?", "Philip K. Dick"],
  ["The Left Hand of Darkness", "Ursula K. Le Guin"],
  ["A Wizard of Earthsea", "Ursula K. Le Guin"],
  ["The Fellowship of the Ring", "J.R.R. Tolkien"],
  ["Eragon", "Christopher Paolini"],
  ["The Lightning Thief", "Rick Riordan"],

  // ---- Thriller / mystery / crime ----
  ["The Da Vinci Code", "Dan Brown"],
  ["Angels & Demons", "Dan Brown"],
  ["The Girl with the Dragon Tattoo", "Stieg Larsson"],
  ["Gone Girl", "Gillian Flynn"],
  ["The Girl on the Train", "Paula Hawkins"],
  ["The Silent Patient", "Alex Michaelides"],
  ["And Then There Were None", "Agatha Christie"],
  ["Murder on the Orient Express", "Agatha Christie"],
  ["The Murder of Roger Ackroyd", "Agatha Christie"],
  ["The Hound of the Baskervilles", "Arthur Conan Doyle"],
  ["The Firm", "John Grisham"],
  ["A Time to Kill", "John Grisham"],
  ["The Pelican Brief", "John Grisham"],
  ["The Shining", "Stephen King"],
  ["It", "Stephen King"],
  ["The Stand", "Stephen King"],
  ["Misery", "Stephen King"],
  ["Carrie", "Stephen King"],
  ["The Bourne Identity", "Robert Ludlum"],
  ["The Girl Who Played with Fire", "Stieg Larsson"],
  ["Big Little Lies", "Liane Moriarty"],
  ["The Reversal", "Michael Connelly"],
  ["Along Came a Spider", "James Patterson"],
  ["The Cuckoo's Calling", "Robert Galbraith"],

  // ---- Romance / contemporary ----
  ["The Notebook", "Nicholas Sparks"],
  ["A Walk to Remember", "Nicholas Sparks"],
  ["Me Before You", "Jojo Moyes"],
  ["Outlander", "Diana Gabaldon"],
  ["It Ends with Us", "Colleen Hoover"],
  ["Verity", "Colleen Hoover"],
  ["The Fault in Our Stars", "John Green"],
  ["Pride and Prejudice and Zombies", "Seth Grahame-Smith"],
  ["The Time Traveler's Wife", "Audrey Niffenegger"],
  ["Where the Crawdads Sing", "Delia Owens"],
  ["Normal People", "Sally Rooney"],
  ["The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid"],
  ["Bridget Jones's Diary", "Helen Fielding"],

  // ---- YA / middle-grade ----
  ["The Hunger Games", "Suzanne Collins"],
  ["Catching Fire", "Suzanne Collins"],
  ["Mockingjay", "Suzanne Collins"],
  ["Twilight", "Stephenie Meyer"],
  ["New Moon", "Stephenie Meyer"],
  ["Divergent", "Veronica Roth"],
  ["The Maze Runner", "James Dashner"],
  ["The Perks of Being a Wallflower", "Stephen Chbosky"],
  ["Looking for Alaska", "John Green"],
  ["The Giver", "Lois Lowry"],
  ["Wonder", "R.J. Palacio"],
  ["Charlotte's Web", "E.B. White"],
  ["Matilda", "Roald Dahl"],
  ["Charlie and the Chocolate Factory", "Roald Dahl"],
  ["The BFG", "Roald Dahl"],
  ["Diary of a Wimpy Kid", "Jeff Kinney"],
  ["The Cat in the Hat", "Dr. Seuss"],
  ["Green Eggs and Ham", "Dr. Seuss"],
  ["Oh, the Places You'll Go!", "Dr. Seuss"],

  // ---- Non-fiction / self-help / memoir ----
  ["Sapiens: A Brief History of Humankind", "Yuval Noah Harari"],
  ["Homo Deus", "Yuval Noah Harari"],
  ["Atomic Habits", "James Clear"],
  ["The 7 Habits of Highly Effective People", "Stephen R. Covey"],
  ["How to Win Friends and Influence People", "Dale Carnegie"],
  ["Think and Grow Rich", "Napoleon Hill"],
  ["Rich Dad Poor Dad", "Robert T. Kiyosaki"],
  ["The Power of Now", "Eckhart Tolle"],
  ["A New Earth", "Eckhart Tolle"],
  ["The Subtle Art of Not Giving a F*ck", "Mark Manson"],
  ["Thinking, Fast and Slow", "Daniel Kahneman"],
  ["Outliers", "Malcolm Gladwell"],
  ["The Tipping Point", "Malcolm Gladwell"],
  ["Educated", "Tara Westover"],
  ["Becoming", "Michelle Obama"],
  ["The Diary of a Young Girl", "Anne Frank"],
  ["Man's Search for Meaning", "Viktor E. Frankl"],
  ["Quiet: The Power of Introverts", "Susan Cain"],
  ["The Body Keeps the Score", "Bessel van der Kolk"],
  ["The Four Agreements", "Don Miguel Ruiz"],
  ["The Power of Habit", "Charles Duhigg"],
  ["Born a Crime", "Trevor Noah"],
  ["The Gifts of Imperfection", "Brené Brown"],
  ["A Brief History of Time", "Stephen Hawking"],
  ["Steve Jobs", "Walter Isaacson"],
];

const POPULAR_BOOKS = RAW.map(([title, author]) => ({
  title,
  author,
  cover: null,
  key: "pop-" + slug(title + "-" + author),
}));

export default POPULAR_BOOKS;
